# To run this:
#  docker-compose up
version: "3.3"
services:
  fibonacci-jvm-server:
    image: hub.docker.com/duckladydinh/fibonacci-jvm-server:1.0-SNAPSHOT
    ports:
      - "9999:9999"
    # container_name: fibonacci-jvm-server
    env_file:
      - docker-environment-variables.env
